apiVersion: v1
kind: Service
metadata:
  name: convertor
  namespace: applications
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: convertor

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: convertor
  namespace: applications
spec:
  replicas: 3
  selector:
    matchLabels:
      app: convertor
  template:
    metadata:
      labels:
        app: convertor
    spec:
      containers:
      - name: convertor
        image: diana1996/convertor:latest
        imagePullPolicy: Always
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /.well-known/live
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 20
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /.well-known/ready
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 20
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources:
          limits:
            cpu: 200m
            memory: 100Mi
          requests:
            cpu: 100m
            memory: 50Mi
        ports:
        - containerPort: 8080
