apiVersion: v1
kind: Service
metadata:
  name: convertor
  namespace: applications
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: convertor

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: convertor
  namespace: applications
spec:
  replicas: 3
  selector:
    matchLabels:
      app: convertor
  template:
    metadata:
      labels:
        app: convertor
    spec:
      containers:
      - name: convertor
        image: diana1996/convertor:latest
        ports:
        - containerPort: 8080
